settings:
  title: '站点监控'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: www.xcheny.cn
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://www.xcheny.cn/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-cloudflare-com
    name: 艾了
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.xn--ykqv08j.top/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: ypan-tk
    name: ypan
    url: 'https://ypan.tk/'
    method: GET
    expectStatus: 200
