settings:
  title: '站点监控'
  url: 'https://cf-workers-status-page-production.xcheny.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有系统正常运行'
  notAllmonitorsOperational: '部分系统未正常运行'
  monitorLabelOperational: '正常'
  monitorLabelNotOperational: '不正常'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '一切正常'
  dayInHistogramNotOperational: ' 个故障记录'  # xx 个故障记录



monitors:
  - id: xcheny # unique identifier
    name: www.xcheny.cn
    description: '个人主页' # default=empty
    url: 'https://www.xcheny.cn/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: aile
    name: 艾了.top
    description: '个人主页'
    url: 'https://www.xn--ykqv08j.top/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: ypan
    name: ypan.tk
    description: '网盘程序'
    url: 'https://ypan.tk/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: wanp
    name: wanp.tk
    description: '网盘程序'
    url: 'https://wanp.tk/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
